### ISSUE TITLE
A better look of the login page

### ISSUE THREAD

**Issue by thebishaldeb** [thebishaldeb/onRoad#7]

**Comment by Andrejkaaa** [comment]
Hi I am interesting to solve the issue #7 Could you please assign it to me? thank you

**Comment by thebishaldeb** [comment]
> Hi I am interesting to solve the issue #7 Could you please assign it to me? thank you

Sure go ahead!

**Comment by Andrejkaaa** [comment]
Hi .. I pull request could you please check and if you want me to change something let me know.

**Comment by Andrejkaaa** [comment]
![emulator](https://user-images.githubusercontent.com/56259088/68532596-89dc3100-031f-11ea-8a81-2c69e29eb09f.png)
